### ISSUE TITLE
Customize the default DL dir for torrents loaded via "watch" folder

### ISSUE THREAD

**Issue by Enissay** [mondediefr/docker-rutorrent#110]
Bonjour,

Ya t il moyen d'envoyer les fichers téléchergé via cette méthode (ajout dans le dossier watch) vers un dossier specifique autre que celui par defaut `/data/downloads`.
Sinon, prière de me suggèrer une alternative ?

En gros, je suis limité en termes d'espace, et je veux que les fichiers téléchargés via le "watch" soient enovoyé vers un autre disque/dossier que j'ai déja monté!

Merci <3

**Comment by Rathorian** [comment]
> Bonjour,
> 
> Ya t il moyen d'envoyer les fichers téléchergé via cette méthode (ajout dans le dossier watch) vers un dossier specifique autre que celui par defaut `/data/downloads`. Sinon, prière de me suggèrer une alternative ?
> 
> En gros, je suis limité en termes d'espace, et je veux que les fichiers téléchargés via le "watch" soient enovoyé vers un autre disque/dossier que j'ai déja monté!
> 
> Merci <3

À ma connaissance, il n'est pas possible de différencier le dossier de téléchargement.
Si tu veux modifier le dossier de téléchargement pour le dossier watch, la modification se fera aussi dans ruTorrent.
