### ISSUE TITLE
Change the default favicon.ico

### ISSUE THREAD

**Issue by Enissay** [mondediefr/docker-rutorrent#12]
Would it be possible to either make it customizable OR change it by default.

I used to change it when installing it manually which gives a feel & look way better than the ugly r logo ^_^

![favicon ico](https://user-images.githubusercontent.com/794673/79508697-502ff480-803a-11ea-8a6c-d5b3676b6894.png)

Thank you for the great work

**Comment by Magicalex** [comment]
Not by default.
You can create a rutorrent extension for this.

**Comment by Enissay** [comment]
@Magicalex Thanks for the feedback. 
I looked around and couldn't find a guide to create one. Do you happen to have some useful link(s) for me ?

**Comment by Magicalex** [comment]
I have no links, you need to inspect code in the rutorrent project.
