### ISSUE TITLE
ajout du plugin ratiocolor

### ISSUE THREAD

**Issue by matt-prod** [mondediefr/docker-rutorrent#121]
Hello @Rathorian,
Possibilité de rajouter le plugin ratiocolor au moment du build ? 
https://github.com/Micdu70/rutorrent-ratiocolor.git

Thanks

**Comment by Rathorian** [comment]
> Possibilité de rajouter le plugin ratiocolor au moment du build ?

Salut @matt-prod ,
Oui je n'y vois pas d'inconvénient.
Il fallait que je mette à jour l'image également, je m'en occupe dans le week-end.

**Comment by Rathorian** [comment]
@matt-prod 

Normalement c'est bon !
