### ISSUE TITLE
Add builder for creating docker image

### ISSUE THREAD

**Issue by stickz** [mondediefr/docker-rutorrent#129]
Hello @Rathorian, I would like to know if you'd like a builder for creating this docker image. If so, I'd be happy to submit a pull request. 

1) It's required to build `dumptorrent` for the new dump plugin on ruTorrent `v5.1`. https://github.com/TheGoblinHero/dumptorrent

2) If you build `mktorrent` with pthreads, it's possible to obtain a 8 times speed improvement for creating torrents on ruTorrent due to multi-threading. https://github.com/pobrn/mktorrent/blob/master/Makefile#L30

3) `rtorrent` is more stable if you build `curl` with `c-ares`. It can hang sometimes and this is preventable.
https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning#name-resolving-enhancements

The build dependencies would **_not_** be added to final image. The only thing remaining would be the optimized software. (dumptorrent, mktorrent, curl, c-ares)

**Comment by lottelucky** [comment]
Support the suggestions made by stickz. Looking forward to the author of this DOCKEr mirror supporting the automatic synchronization of major rutorrent version updates in the novik project, thank you!

**Comment by Rathorian** [comment]
Hello @stickz ,

Indeed, I think that improvements are necessary.

Not having much time to take care of it lately, I would be delighted with your help, I accept gladly.

Thank you very much
