### ISSUE TITLE
exec format error (latest:filebot)

### ISSUE THREAD

**Issue by petsasj** [mondediefr/docker-rutorrent#13]
Got your container up and running for a few weeks now.

Watchtower updated to the latest image a few days ago.

No ports are being published, and I investigated further.
Logs have the following error:

> standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by Magicalex** [comment]
What is your arch?

**Comment by petsasj** [comment]
Using Centos 7 64 bit if that's what you're asking

**Comment by Magicalex** [comment]
Can you retry? `docker pull mondedie/rutorrent:latest`

**Comment by petsasj** [comment]
I am a little confused: You have two images?
One is plain rutorrent and one is filebot?

I have always been using rutorrent:filebot

Now with rutorrent:latest it works

**Comment by Magicalex** [comment]
yes, one image without filebot (tag latest) and one with filebot (tag filebot)

**Comment by petsasj** [comment]
Right, ok, so rutorrent:filebot is the one I want.

But it still has the same issue as posted earlier

**Comment by Magicalex** [comment]
Please can you paste the output of `docker info`

**Comment by petsasj** [comment]
Just want to point out again that this was working well until 3 days ago.

Here you go.

> docker info
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1127.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 15.45 GiB
Name: router
ID: BM35:6E2Y:QMOO:2YPE:2G7S:GUA3:HTUX:MM4Z:LQXC:NMC5:IFWI:H2PX
Docker Root Dir: /mnt/WDRed/Centos/libs/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

**Comment by Magicalex** [comment]
> Just want to point out again that this was working well until 3 days ago.

I know, but recently I dropped support for 32-bit arch.
This error is typically due to bad arch [see this](https://stackoverflow.com/questions/42885538/raspberry-pi-docker-error-standard-init-linux-go178-exec-user-process-caused/42886112#42886112)

**Comment by petsasj** [comment]
I am running a 64-bit arch at the moment.

Is this error associated with something that went wrong during the build of the image, or did you stop supporting my arch altogether?

**Comment by Magicalex** [comment]
> Is this error associated with something that went wrong during the build of the image, or did you stop supporting my arch altogether?

No because the image works and your arch is supported, so I don't undestand.

**Comment by petsasj** [comment]
I do not understand why, but it works.

Removed the image, pulled again, and it starts the container.

I had tried the same step yesterday, but it didn't work.

Did you update something or am I losing my mind?

**Comment by Magicalex** [comment]
Yes you can chack all builds here https://github.com/mondediefr/docker-rutorrent/actions

**Comment by petsasj** [comment]
Right, okay.

Thanks a lot for your time again.

I think it's safe to close this now?

PS: Do you have a donation link? So I can buy you a beer or something for your troubles?

**Comment by Magicalex** [comment]
Thanks I have a [paypal account](https://paypal.me/AlexandreLevionnais)

Yes I think it's safe to close.

**Comment by petsasj** [comment]
Sent 

Thanks again, closing.

**Comment by Magicalex** [comment]
Thank you :)
