### ISSUE TITLE
problem mktorrent

### ISSUE THREAD

**Issue by bouba89** [mondediefr/docker-rutorrent#137]
Bonjour Rathorian ( je suis Diesel ) je suis passé en version 5.1 mai apparament grosse coquille pas moyen de creer un .torrent

/rutorrent/app/plugins/create/mktorrent.sh: line 11: /usr/bin/mktorrent: not foundchmod: /rutorrent/app/share/users/diesel/settings/tasks/1732866530674971e2085995.75738865/temp.torrent: No such file or directory

**Comment by stickz** [comment]
Bonjour @bouba89. Merci pour le rapport. J'ai résolu le problème. J'ai oublié de changer l'emplacement en `/usr/local/bin`.

mktorrent a été mis à jour pour créer des torrents 4 à 8 fois plus rapidement.
