### ISSUE TITLE
Old version of libjnidispatch gives me errors

### ISSUE THREAD

**Issue by Glazastik** [mondediefr/docker-rutorrent#14]
java.lang.Error:
There is an incompatible JNA native library installed on this system
Expected: 6.1.0
Found:    5.2.2
(at /filebot/lib/Linux-x86_64/libjnidispatch.so).

**Comment by Magicalex** [comment]
I have the same error

**Comment by Magicalex** [comment]
You can pull the newer image and test?

**Comment by Glazastik** [comment]
Works fine, thank you!
