### ISSUE TITLE
Error : su-exec: /bin/s6-svscan: No such file or directory

### ISSUE THREAD

**Issue by Rathorian** [mondediefr/docker-rutorrent#142]
Hello @stickz ,

I wanted to update Alpine Linux to version 3.21 at the same time as ruTorrent but I realize that changes have been made.

We end up with an error when launching the application and suddenly the image restarts in a loop:
`su-exec: /bin/s6-svscan: No such file or directory
`

Do you have any idea what changes to make?

Thank you

**Comment by njd90** [comment]
Hello, 

Je viens de mettre à jour et je rencontre le meme problème. 
`rutorrent  | su-exec: /bin/s6-svscan: No such file or directory`

**Comment by koogaak** [comment]
Même problème ici :)
