### ISSUE TITLE
replace d.directory by d.base_path

### ISSUE THREAD

**Issue by zethis** [mondediefr/docker-rutorrent#16]
Hello can you modify this ?

`sed -e "s|d\.directory|d\.base_path|g" -i /config/rtorrent/.rtorrent.rc`

I need "d.directory.set" in my .rtorrentrc, it's replaced by d.base_path.set, who doesn't exist.

Thanks :)

**Comment by Magicalex** [comment]
I fix this as soon as possible

**Comment by Magicalex** [comment]
@zethis can you retry?
