### ISSUE TITLE
JS = TypeError: table is null

### ISSUE THREAD

**Issue by Rathorian** [mondediefr/docker-rutorrent#18]
Bonjour,

Depuis la dernière version, j'ai une erreur récurrente sur l'image docker (version avec FileBot).

Dans le journal de ruTorrent, j'ai cette erreur là : 
`JS error: [https://rutorrent.domaine.fr/js/jquery.js line 2 > eval : 3717] TypeError: table is null`

Je dois très régulièrement redémarrer le container pour ne plus avoir l'erreur.
Aucune erreur particulière pour cette erreur dans les logs du container.

J'ai parfois même plus du tout accès au GUI mais pour le coup, j'ai pas pensé à regarder les logs.
Si ça revient, je posterais les logs.

Merci

**Comment by Magicalex** [comment]
Y a de forte chance que le problème vient du coté client.

**Comment by Rathorian** [comment]
Salut,

Tu penses que le problème viendrait d’où coté client ?
Dernière version de Firefox, j'utilise Traefik en reverse proxy.

Je ne vois vraiment pas d’où cela pourrait venir.
J'ai fait un peu le tour mais là je suis un peu bloqué.

J'ai beau redémarrer le conteneur, au bout d'un certain temps, j'ai ce fameux message d'erreur qui persiste à revenir

**Comment by Hydrog3n** [comment]
@Rathorian Tu aurais moyen d’investiguer un peu plus pour savoir plus?

**Comment by Rathorian** [comment]
Oui bien sur.
Je sais pas vraiment ou chercher mais je vais me renseigner

**Comment by Hydrog3n** [comment]
Je serais pas te dire non plus car j'ai jamais eu ce soucis.

**Comment by Rathorian** [comment]
J'ai supprimé le dossier "conf" de rutorrent pour repartir sur une base seine.

L'erreur réapparait malgré tout mais je me suis aperçu qu'en faisant un "Ctrl + F5" pour vider le cache, l'erreur disparait....
J'avoue ne pas trop comprendre pourquoi !!!

Auriez-vous une idée ?

**Comment by Hydrog3n** [comment]
Oui je pense qu'il y a un soucis dans rutorrent est que c'est pas de notre coté.

**Comment by Rathorian** [comment]
C'est étonnant d'être le seul impacté tout de même....

**Comment by Hydrog3n** [comment]
Oui mais va savoir... 
Essaye d'ouvrir une issue sur le repo rutorrent.

**Comment by Magicalex** [comment]
@Rathorian quand l'erreur apparait, ouvre l'outil de développement et regarde si y a un message d'erreur dans la console.

**Comment by Rathorian** [comment]
@Magicalex  Voici les erreurs retournés dans la console :

```
Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». rutorrent.domaine.fr
Le cookie « browser_timezone » sera bientôt rejeté car son attribut « SameSite » est défini sur « None » ou une valeur invalide et il n’a pas l’attribut « secure ». Pour en savoir plus sur l’attribut « SameSite », consultez https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite common.js:1596:62
Une chaîne vide a été transmise à « getElementById() ». jquery.js:2:24934
Une chaîne vide a été transmise à « getElementById() ». 81 common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
Une chaîne vide a été transmise à « getElementById() ». common.js:8:43
```

**Comment by Hydrog3n** [comment]
ça semble plus des warning les deux 1ere lignes. Tu as pas un thème custom ou un thème spécial ?

**Comment by Rathorian** [comment]
@Hydrog3n  J'utilise le thème fourni dans l'image (materialdesign)

Là, en allant voir, je n'avais plus du tout accès et avec un "Ctrl + F5" c'est revenu : 

![](https://wtf.roflcopter.fr/pics/vOQIPySq/xhVwJXWR)

Aucun message d'erreur, même dans la console développeur, mise à part les 2 premiers cités dans mon dernier message.

**Comment by Hydrog3n** [comment]
J'ai vraiment aucune idée de ou ça peut venir. J'utilise aussi ce thème.

**Comment by Rathorian** [comment]
@Hydrog3n D'accord, bah écoute on va attendre de voir si ça répond dans l'issue que j'ai fait sur le Github de ruTorrent.
Merci en tout :)

**Comment by Rathorian** [comment]
Aucune nouvelle pour le moment, à croire que je suis vraiment le seul à avoir ce problème et il est toujours d'actualité.

**Comment by Magicalex** [comment]
Tu peux tester avec un autre navigateur?

**Comment by Rathorian** [comment]
> 
> 
> Tu peux tester avec un autre navigateur? ça peut venir d'un plugin de ton navigateur?

J'ai suivi ton conseil en utilisant le seul autre navigateur d'installé sur mon PC (Microsoft Edge) et effectivement c'est très bien vu et je n'y avais pas pensé car avec Edge, je n'ai pas d'erreur alors qu'au même moment avec Firefox j'ai le problème en question.

Je vais essayé de voir en désactivant un par un quel est le plugin qui fou la merde car j'en ai quelques uns :)

Merci à toi @Magicalex
