### ISSUE TITLE
Suppression de contenu depuis le filemanager

### ISSUE THREAD

**Issue by Whisper40** [mondediefr/docker-rutorrent#19]
Sur une nouvelle installation, avec la version latest de ton image, il m'est impossible de supprimer un fichier depuis le filemanager en faisant clique droit supprimer. L'action est dite réalisée, alors que le fichier reste présent.

PS : Je peux supprimer un fichier depuis l'interface clique droit supprimer avec données, mais pas depuis le filemanager...

Il n'a pas un problème d'incompatibilité par hasard ?
Cette version semble être l'actuelle à utiliser : https://github.com/nelu/rutorrent-filemanager

**Comment by Whisper40** [comment]
Problème confirmé par une autre personne en MP

**Comment by Magicalex** [comment]
Ok, je regarde as soon as possible...

**Comment by Whisper40** [comment]
Salut, as tu des news ?

**Comment by Magicalex** [comment]
J'ai trouvé le message d'erreur
`"PHP message: PHP Notice:  Only variables should be passed by reference in /rutorrent/app/plugins/filemanager/flm.class.php on line 104`

Mais je sais pas comment le résoudre pour le moment.

**Comment by Whisper40** [comment]
Tu as pu voir ce qui arrivait comme data à la méthode par rapport à l'attendu ?

**Comment by Magicalex** [comment]
@Whisper40 tu peux tester le fix?
