### ISSUE TITLE
Question : L'image change d'elle même les droits des volumes host..

### ISSUE THREAD

**Issue by Whisper40** [mondediefr/docker-rutorrent#21]
Pourquoi l'image chnage t-elle les droits ?

J'ai mis cette option : CHECK_PERM_DATA=false   et malgré tout, elle modifie les droits..
Avant le démarrage le dossier data est en whisper:www-data
et après le démarrage du conteneur avec cette image, le conteneur passe en whisper:whisper..

Ayant besoin d'utiliser le dossier data avec nextcloud aussi, j'ai besoin de pouvoir garder whisper:www-data..

**Comment by Magicalex** [comment]
Réutilise les bon UID GID

**Comment by Whisper40** [comment]
En indiquant uniquement l'uid sans indiquer le gid c'est passé ! ;) Merci
Sinon j'aurais du mettre gid:33 dans mon cas
