### ISSUE TITLE
Déplacer un fichier depuis le filemanager

### ISSUE THREAD

**Issue by Whisper40** [mondediefr/docker-rutorrent#22]
Salut, je crois qu'il y a un autre problème ( pas pu le confirmer vu que la seule image dispo est "latest", j'aurais voulu revenir en arrière pour tester).
Il semblerait que depuis le filemanager, un clique droit puis déplacer soit à chaque fois en "failed" que ce soit un fichier ou un dossier.
Depuis un autre programme la même action est ok..
![image](https://user-images.githubusercontent.com/30440458/113355226-b93e7400-9340-11eb-9d32-43d356ca6d40.png)
![image](https://user-images.githubusercontent.com/30440458/113355277-ce1b0780-9340-11eb-9e36-d71d2908fa4a.png)

**Comment by Whisper40** [comment]
@Magicalex Salut, tu as pu tester de ton côté ?

**Comment by Magicalex** [comment]
Tu peux tester?

**Comment by Whisper40** [comment]
Parfait c'est ok ;)
