### ISSUE TITLE
Image buildée et pushée causant un plantage de rutorrent

### ISSUE THREAD

**Issue by Whisper40** [mondediefr/docker-rutorrent#25]
@Hydrog3n Salut, ton build a fail et a été push dans dockerhub, ce qui a causé le plantage de rutorrent lors de la récupération de l'image..
Pourrait tu revenir en arrière sur cette modif et rebuilder

Il faudrait aussi mettre des tags sur cette image pour éviter au maximum ce genre de problème et pourquoi pas faire des tests pour s'assurer que l'image est fonctionnelle avant de builder :)

**Comment by Hydrog3n** [comment]
Oula Sorry je vais corrigé ça de suite.

**Comment by Whisper40** [comment]
@Hydrog3n Voilà l'erreur actuelle suite au pull de l'image ( l'ancienne datait de 9 jours ) 
![image](https://user-images.githubusercontent.com/30440458/148825625-27bc8694-8e98-4a24-ac1c-5e73d90a3fe3.png)

Je repull une fois le build ok et je te dis

**Comment by Hydrog3n** [comment]
coté log tu as des choses dans les logs quand tu fais docker logs rutorrent ?

**Comment by Whisper40** [comment]
```
[2022/01/10-19:05:35] Create torrent user... done
[2022/01/10-19:05:35] Create volume folders... done
[2022/01/10-19:05:35] Generate configuration... done
[2022/01/10-19:05:35] HTTP authentication configuration... done
[2022/01/10-19:05:35] Update old configurations... done
[2022/01/10-19:05:35] Apply system permissions... done
[2022/01/10-19:05:35] Apply data permissions... done
```

**Comment by Hydrog3n** [comment]
Ok mince... car sur la version arm ça démarre pas j'ai une erreur... Tu me diras si le nouveau build est mieux. C'est pas bien de faire de l'auto pulling :P

**Comment by Whisper40** [comment]
Héhé non pas de l'auto pulling ;) 
C'est qu'en fait j'ai demandé un build à Magicalex suite à un bug dans rutorrent qui avait été corrigé il y a quelques jours
Voyant le build j'ai dessuite recrée le conteneur ;) 

Sauf que.. voilà..

**Comment by Whisper40** [comment]
D'où le besoin de créer des tags :) 
Même si les tags sont pas utilisés par les gens, mais au moins il permet de trouver un palliatif très rapide à ce type de problème

**Comment by Hydrog3n** [comment]
Ok ça marche. Tu me dis je vais regarder comment tagger tout ça.

**Comment by Whisper40** [comment]
Là c'est étrange ! J'ai toujours la même erreur..
Chargement classique puis ça.. 
![image](https://user-images.githubusercontent.com/30440458/148828779-c62262aa-4826-4809-a12d-e47406ada198.png)

**Comment by Whisper40** [comment]
Désolé, le bug n'est pas ton commit mais est finalement avec rutorrent en lui même ! ( j'ai testé sur un deuxième serveur !)

T'as une solution ? (à la place de cloner rutorrent master, cloner un le tag d'il y a 9 jours ?)

**Comment by Hydrog3n** [comment]
ok donc c'est plus un pb avec rutorent directement...

**Comment by Hydrog3n** [comment]
normalement tu dois avoir ton image encore si tu prune pas tes images. Si tu retire le latest il devrais lancer celle avant qu'il trouve

**Comment by Whisper40** [comment]
Merci ;) Vu que je l'ai fais à la main c'est ok, heureusement que watchtower n'est pas passé par là !
D'ou encore le besoin des tags :)
