### ISSUE TITLE
Doesn't work anymore - automatic update 

### ISSUE THREAD

**Issue by Merrick28** [mondediefr/docker-rutorrent#26]
The latest tag doesn't work : 

![image](https://user-images.githubusercontent.com/3830148/148911712-4e52ab0d-6bd0-4fb2-b46a-48f5eb21a477.png)

The update was made tonight, automatically I guess : 

![image](https://user-images.githubusercontent.com/3830148/148911808-f85d26ed-2cb5-411f-ba47-8cf9f99a2ed7.png)

**Comment by Hydrog3n** [comment]
Hello yes, we notice that with the last build it's not on our site it's more rutorrent problem.

**Comment by Whisper40** [comment]
@Merrick28 We discussed about this yesterday here : https://github.com/mondediefr/docker-rutorrent/issues/25

Issue has been reported here : https://github.com/mondediefr/docker-rutorrent/issues/25

And the fix seems to be there : https://github.com/Micdu70/geoip2-rutorrent

**Comment by Merrick28** [comment]
OK, I close (et la prochaine fois je le ferai en français, ce sera plus simple :D )

**Comment by Merrick28** [comment]
L'interface est ok, mais le chemin des torrents que j'ai dans ma conf n'est pas pris en compte :+1: 
11.01.2022 16:36:44] WebUI started.
[11.01.2022 16:36:49] Le serveur Web ne peut pas accéder au dossier des torrents en Lecture/Écriture/Exécution. Vous ne pouvez pas ajouter de torrents via ruTorrent. (/rutorrent/app/php/share/torrents)
[11.01.2022 16:36:49] rTorrent ne peut pas accéder au dossier des torrents en Lecture/Écriture. Vous ne pouvez pas ajouter de torrents via ruTorrent. (/rutorrent/app/php/share/torrents) <== ça devrait être /home/seed/local/rutorrent

![image](https://user-images.githubusercontent.com/3830148/148973286-7491d4c0-32dd-4637-a52a-b76ba8dea8d9.png)

**Comment by Hydrog3n** [comment]
Il y a pas une env qui a changé peut être.

**Comment by Whisper40** [comment]
@Merrick28 Hum je vois pas ce problème
Quand j'ajoute un torrent, il va bien dans le répertoire demandé

**Comment by Merrick28** [comment]
Bon, un petit chmod des familles a résolu mon problème a priori...

**Comment by Hydrog3n** [comment]
Ok good news alors. Peut être le précédent build a mit le bazars dans ta conf

**Comment by Merrick28** [comment]
Il semble que les vars UID et PID ne soient pas respectés (d'où mon souci de droits)
```
(venv) seed@seedhz:~/local/rutorrent$ docker inspect rutorrent | egrep "(G|U)ID"
                "UID=1000",
                "GID=1000",
```

```
venv) seed@seedhz:~/local/rutorrent$ docker exec -it rutorrent bash
bash-5.1# id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
```

**Comment by Hydrog3n** [comment]
Tu as les log de start ? https://github.com/mondediefr/docker-rutorrent/blob/master/rootfs/usr/local/bin/startup#L30

**Comment by Hydrog3n** [comment]
utilise sh aussi pour exec

**Comment by Merrick28** [comment]
J'ai du m'emballer... en fait, on arrive en root sur un exec, je pensais qu'on arrivait sur le user par défaut ? Mais on a bien un user 1000:1000

Logs de démarrage : 
```
[2022/01/12-07:46:56] Create torrent user... done
[2022/01/12-07:46:56] Create volume folders... done
[2022/01/12-07:46:56] Generate configuration... done
[2022/01/12-07:46:56] HTTP authentication configuration... done
[2022/01/12-07:46:56] Update old configurations... done
[2022/01/12-07:46:56] Apply system permissions... [2022/01/12-07:46:59] Create torrent user... done
[2022/01/12-07:46:59] Create volume folders... done
[2022/01/12-07:46:59] Generate configuration... done
[2022/01/12-07:46:59] HTTP authentication configuration... done
[2022/01/12-07:46:59] Update old configurations... done
[2022/01/12-07:46:59] Apply system permissions... done
[2022/01/12-07:47:01] Apply data permissions... done
```

```
(venv) seed@seedhz:~$ docker exec -it rutorrent sh
/ # cat /etc/passwd
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
nginx:x:100:101:nginx:/var/lib/nginx:/sbin/nologin
catchlog:x:101:102:catchlog:/:/bin/false
torrent:x:1000:1000:Linux User,,,:/home/torrent:/bin/sh
/ # su - torrent
066b270a349d:~$ 
```
