### ISSUE TITLE
Bug last version

### ISSUE THREAD

**Issue by snaj06** [mondediefr/docker-rutorrent#28]
Hello,

Je crois qu'il y a un souci avec la version de cette nuit (et je vois un built en ko).

De mon côté suite à la maj auto (watchtower) le docker ne se lance plus depuis ce matin et l'image que je récupère est pour linux/arm/v7 alors que je devrais avoir comme avant, celle pour amd64.

J'ai voulu mettre l'ancienne version mais j'ai l'impression que pour ce projet, les releases anciennes ne sont pas dispo.

**Comment by Whisper40** [comment]
@snaj06 Oui un bug est présent
Logs d'erreurs: 
```
standard_init_linux.go:228: exec user process caused: exec format error
```

Malheureusement, les tags ne sont pas encore dispos pour revenir à une image fonctionnelle.
J'espère pour toi que tu n'as pas purgé l'image avec watchtower comme ça tu peut revenir à une ancienne version

**Comment by snaj06** [comment]
Avec watchtower mes images sont purgées donc actuellement je suis bloqué, à part changer de version d'image. C'est dommage de ne pas avoir de versionning et donc une section release qui permettant, en cas de problème, de revenir à l'image d'avant. Contrairement à la dernière fois (semaine dernière, je n'ai plus aucun torrent en seed cette fois et une erreur http 502.

Je suis pour ta méthode @Wisper40 et j'espère que le bug sera corrigé rapidement, car depuis ce matin, je suis bloqué.

**Comment by Whisper40** [comment]
@snaj06 Je laisse les experts @Hydrog3n @Magicalex  regarder la proposition de pull request que j'ai fais et voir si le code est OK.
Actuellement oui tu es malheureusement bloqué :( 
Proposer des images en "latest" est une trés mauvaise pratique, qu'il faut vraiment corriger..

**Comment by snaj06** [comment]
Merci pour tes infos en tout cas :) si demain c'est tjr pas corrigé je pense migrer sur linuxserver/rutorrent. J'avais pris cette version mondedie pour le plugin filemanager qui était intégré et bien pratique. L'arbo des 2 container est bien différente donc y'a qq fichier à déplacer pour migrer donc j'attends demain pour voir :)

**Comment by zethis** [comment]
Pour fix en attendant => 
1. git clone https://github.com/mondediefr/docker-rutorrent.git
2. git checkout 7381330ac72e921675b15efb219e2c8aad58a9ff (last working commit)
3. docker build -t rutorrent:test .
4. Replace image: mondedie/rutorrent:latest by image: rutorrent:test
5. docker run or docker-compose as you want.

**Comment by zethis** [comment]
Pour rebondir sur les propos de @Whisper40, non atest n'est pas une mauvaise pratique, si les plus grands du monde docker le font c'est pour une bonne raison.
Par contre l'image dois toujours être au minimum double taggué.
Si la version 1.x est la latest alors je tag 1.x ET latest, pareil pour les prochaines version.
Comme ça ca permet de sticker une version spécifique pour ceux qui le veulent et pour d'autre être toujours sur la dernière version (même si cela inclus un risque).

Bonne journée ;)

**Comment by Hydrog3n** [comment]
Hello, J'ai revert le dernier merge. Le build sera donc disponible dans 20/30min

**Comment by snaj06** [comment]
Merci !

**Comment by ShagoY** [comment]
Cela fonctionne pour vous ?

Je viens de mettre à jour et contrairement à hier, je ne peux plus ajouter de torrent sur ce build.
J'avais utilisé le correctif sur le avant-dernier build: 
`````
docker exec -it rutorrent mkdir /rutorrent/app/php/share/torrents
docker exec -it rutorrent chown torrent: /rutorrent/app/php/share/torrents
docker restart rutorrent
`````

**Comment by Whisper40** [comment]
@ShagoY Pour moi l'ajout à toujours été OK, même avec les builds précédents 
![image](https://user-images.githubusercontent.com/30440458/149813162-728e1ac3-9c4a-4e5d-bf75-4de85b7a1b0c.png)

**Comment by ShagoY** [comment]
J'ai le même msg au démarrage mais je ne sais pas pourquoi impossible d'ajouter un torrent contrairement à hier :(
