### ISSUE TITLE
Changement de repo pour filemanager et fileshare ...

### ISSUE THREAD

**Issue by Whisper40** [mondediefr/docker-rutorrent#31]
Dans le Dockerfile, le repo cloné est celui-ci : https://github.com/nelu/rutorrent-thirdparty-plugins
Le repo est périmé et engendre des erreurs dans rutorrent depuis 2 semaines.
Il faudrait migrer vers ces repos : 
https://github.com/nelu/rutorrent-filemanager
https://github.com/nelu/rutorrent-filemanager-share
https://github.com/nelu/rutorrent-filemanager-media

**Comment by Hydrog3n** [comment]
Hello, tu pense que c'est ça le soucis avec les builds qui marché pas ?

**Comment by Whisper40** [comment]
Non ce n'est pas ça pour le build, par contre en utilisant ces repos ça va résoudre le problème du filemanager que j'ai signalé il y a une semaine et qui a été fix coté filemanager

**Comment by Hydrog3n** [comment]
Ok Je regarde ça quand je peux :)

**Comment by Hydrog3n** [comment]
J'ai fait des modifications il manquait le dossier php/share/torrents je l'ai créé vide + changé le repo filemanager

**Comment by Whisper40** [comment]
Ok pour les modifs je test une fois le build terminé, pas moyen d'ajouter le fileshare et media ?

Regarde ma pullrequest aussi stp si t'as le temps

**Comment by Hydrog3n** [comment]
Ah j'ai pas voulu car tout le monde ne l'a pas tu peux l'ajouter avec les plugins extra je pense.

**Comment by Whisper40** [comment]
D'accord je vois , le truc chiant c'est qu'ils sont hors image donc dès qu'une évolution est nécessaire..beh il faut faire un script à X endroits :( 

Ou alors que je fasse une image qui se base sur celle-ci..

**Comment by Whisper40** [comment]
@Hydrog3n Hum, je crois que ça marche pas 
![image](https://user-images.githubusercontent.com/30440458/149839375-964efdd1-16c9-452a-a322-b8c8c1529e9d.png)
