### ISSUE TITLE
Separation of processes

### ISSUE THREAD

**Issue by nelu** [mondediefr/docker-rutorrent#35]
Hi, just noticed this project and i see it runs all app processes (webserver, php-fpm, bot, etc) in a single container. 
Ideally it would be nice to run only one process per container (a general guideline)  - see this https://www.tutorialworks.com/containers-single-or-multiple-processes/
This can be achieved by using a different command to start each container process (see this docker compose project: https://github.com/nelu/rutorrent-dock/blob/5a66d022a1789515390162c222ad0a0631b7bb30/docker-compose.yml#L50 )

Also using nginx+fpm seems overkill for the task at hand

**Comment by Hydrog3n** [comment]
Hello @nelu, I agree with you about the container concept but to make easier to install and handle we prefer to do like that.
