### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by snaj06** [mondediefr/docker-rutorrent#36]
Hello,

J'ai cette erreur dans l'interface rutorrent quand je lance ma commande docker depuis qu'il y a quelques soucis avec les nouvelles releases : 

`JS error: [https://xxx/js/webui.js : 611] Uncaught TypeError: Cannot set properties of undefined (setting 'webui.lang')`

Par contre, tous mes torrents sont bien en seed, c'est uniquement rutorrent qui ne s'affiche pas.

Merci

**Comment by jean-luc-56** [comment]
Salut,
J'en ai un peu plus:
[https://zupimages.net/viewer.php?id=22/03/r8bb.png](url)

**Comment by Hydrog3n** [comment]
@jean-luc-56 On dirait plus des soucis avec le plugin filedrop il est natif ou externe ?

**Comment by Whisper40** [comment]
@snaj06 idem ici

**Comment by Whisper40** [comment]
Ok this is just a cache problem..
Issue can be closed

**Comment by jean-luc-56** [comment]
@Hydrog3n  C'était Filedrop natif ; j'ai vidé le cache, et c'est ok maintenant, je n'ai plus que celle-ci:
Manipulation des archives désactivée (applications introuvables)rar

**Comment by snaj06** [comment]
Je confirme, ça fonctionne chez moi et je n'ai plus que l'erreur rar "Manipulation des archives désactivée (applications introuvables)rar".
