### ISSUE TITLE
Traffic

### ISSUE THREAD

**Issue by WassabiFR** [mondediefr/docker-rutorrent#37]
Depuis le dernier pull, plus de traffic en historique.
Pourtant les données sont bien présentes dans config/rutorrent/share/settings/trafic

**Comment by Whisper40** [comment]
Même problème, tu devrais le signaler sur le repo suivant https://github.com/Novik/ruTorrent/issues

**Comment by Aerya** [comment]
Je pense que ça ne concerne que ce Docker, que je n'utilise plus. 
Tout est normal avec d'autres : 
![](https://i.imgur.com/DFL7V1w.png)

**Comment by Whisper40** [comment]
@Aerya  
Le problème semble avoir été résolu, le pull d'il y a 2 jours semble avoir embarqué la correction

**Comment by Hydrog3n** [comment]
@WassabiFR C'est bon pour toi ?

**Comment by Whisper40** [comment]
@Hydrog3n Hum, finalement non je crois bien que ce bug est encore présent, je ne vois pas d'évolution du graph malgré qu'il soit bien construit..

**Comment by WassabiFR** [comment]
non le pull n'a pas corrigé la problématique. 
A priori il y a eu encore un nouveau pull et j'ai encore reperdu toute mes configurations:
- de flux RSS, 
- le gestionnaire des règles de ratio,
- Autotools,
- Ratio.

**Comment by Whisper40** [comment]
Pour les configurations, je te laisse regarder les PR en attente, tant qu'elles ne sont pas mergees les configurations sont perdues 
@Hydrog3n

**Comment by Whisper40** [comment]
Correction dans le push #44 
Issue à fermer 
![image](https://user-images.githubusercontent.com/30440458/151574101-eefaccd7-674c-4cf6-a4b4-2de0626ca30c.png)

**Comment by WassabiFR** [comment]
HEllo, via portainer j'ai recréer le conteiner en faisant un pull image et je n'ai toujours pas l'historique de traffic .
Il reste noir malgré une activité download / Upload

**Comment by Whisper40** [comment]
@WassabiFR  
C'est bien fonctionnel.. vérifie bien que tu pars depuis latest..
Mais sinon je ne sais pas quoi te dire, on utilise la même image..
![image](https://user-images.githubusercontent.com/30440458/151704783-1cf1b058-580b-4fe0-a267-cc3ea7b27276.png)
![image](https://user-images.githubusercontent.com/30440458/151704788-e93867fe-3f42-4e14-b36a-025356b4da51.png)
![image](https://user-images.githubusercontent.com/30440458/151704792-ab87e6d0-fb1a-4f22-a25a-9a7f4ca238b1.png)
