### ISSUE TITLE
Utilité ? rootfs/rutorrent/app/plugins/rutorrent-filemanager/conf.php

### ISSUE THREAD

**Issue by Whisper40** [mondediefr/docker-rutorrent#40]
Ce répertoire est présent, mais n'agit en rien lors du build..
Un COPY est réalisé à la fin du build, mais n'agit pas sur le bon répertoire..
![image](https://user-images.githubusercontent.com/30440458/150835651-89335f5e-44c7-4de9-b3bf-7c6dc16441c0.png)

Le dossier n'aurait pas du se nommer "rutorrent-filemanager" mais "filemanager" et là oui il aurait un impact.
Par contre modifier un fichier avec un COPY n'est pas une bonne pratique.. surtout quand on part de master depuis le repo filemanager.
L'idéal aurait été de modifier les champs avec des sed ou équivalents..
Mais on peut clairement avouer qu'en 5 ans, il a pas bougé.. donc autant le garder tel quel

**Comment by Hydrog3n** [comment]
Normallement c'est le bon nom car je fais ceci : https://github.com/mondediefr/docker-rutorrent/blob/master/Dockerfile#L110

**Comment by Hydrog3n** [comment]
Ok c'est une erreur en effet :/
