### ISSUE TITLE
Le container n'écoute pas sur 8080

### ISSUE THREAD

**Issue by imTHAI** [mondediefr/docker-rutorrent#45]
Hello,

Le container que je crée n'écoute sur rien. Y aurait-il eu un changement dans un des derniers update qui aurait cassé ça ?
On dirait que nginx n'est pas lancé
Si je rentre dans mon container et que je lance nginx moi-même, c'est bon, j'accede bien à l'interface web de rutorrent.

```
$ ls /bin/s6-svscan
ls: /bin/s6-svscan: No such file or directory
```

**Comment by imTHAI** [comment]
J'avais p-e un mauvais cache, c'est résolu, par contre il met bcp de temps avant de lancer nginx, il y a avant un process:
find /data ! -user 99 -exec chown -h 99:991 {} ;

Mais ce n'est pas sencé check les perm dans le folder de download (/data/downloads) ? Parce que la il scan les Media compris.

Mon volume est:
` '/mnt/user/data/':'/data':'rw'`

**Comment by Rathorian** [comment]
Salut,

Personnellement je trouve que c'est préférable de laisser ainsi, ça permet d'avoir une cohérence des droits.
Tout le répertoire qui t'appartiens (utilisateur) à les bons droits directement ou pas suivant si c'est activé ou non.

**Comment by imTHAI** [comment]
> Hello,
> Faudrait adapter le README alors.

https://github.com/mondediefr/docker-rutorrent/commit/0174b898e0970abc528f0bdbdd58f3e87d2fb917
👍
