### ISSUE TITLE
Watchtower

### ISSUE THREAD

**Issue by snaj06** [mondediefr/docker-rutorrent#46]
Hello,

Cela fait 6 jours d'affilé que watchtower me dit qu'il y a une nouvelle image mondedie/rutorrent:latest (et donc maj image, relance du docker etc).
Est-ce que je suis le seul ? Car je n'ai pas l'impression qu'il y ait des modifs chaque jour quand je regarde le code.

Merci

**Comment by Hydrog3n** [comment]
Salut, nous avons fait des changement avec latest et les tags. Il y a maintenant des versions journalières. Il y a un tag par mois année et jour. Pour le moment il y aucun moyen de bloqué je te conseil de choisir un jour et de mettre a jours de temps en temps. On va regarder pour qu'il y ai un tag plus stable.

**Comment by snaj06** [comment]
Merci pour l'info ! Le but des tags n'est pas d'avoir un nouveau tag uniquement quand il y a des modifs apportées (un peu comme c'est partout ailleurs je crois) ?

Je ne comprends pas trop l'intérêt de mettre à jour chaque nuit une nouvelle image s'il n'y a pas de nouvelles modifs ?

**Comment by Hydrog3n** [comment]
Merci pour la leçon je sais mais le soucis c'est que l'on utilise pas mal de services qui sont mit a jour fréquemment. On a pour le moment choisi cette stratégie d'ailleurs c'était déja le cas avant sauf que c'était toutes les semaines.

**Comment by Whisper40** [comment]
@snaj06 Le build journalier est tout à fait normal et logique car l'image dépend de rutorrent qui est récupéré depuis Master.
Par conséquent, chaque tag journalier, peut apporter des modifications venant de rutorrent.

Ce type de tag v1.4.1 concerne le projet source en lui même mais en aucun cas valable pour notre cas vu que l'on pull rutorrent depuis master...
L'avantage de cette démarche est de proposer à la fois quelque chose de fixe à l'utilisateur, mais aussi proposer les dernières fonctionnalités.

Donc "Je ne comprends pas trop l'intérêt de créer chaque jour une nouvelle image s'il n'y a pas de nouvelles modifs ?" n'est pas valable car oui il y a des modifs très souvent ( voir plusieurs fois par jour ! )

Sinon il faudrait pull en fonction des changements apportés côté rutorrent ( autant te dire que c'est du travail pour rien sachant que ça bouge de leur côté en continu)

"Car je n'ai pas l'impression qu'il y ait des modifs chaque jour quand je regarde le code." 
-> Je te laisse regarder le dockerfile et te rendre compte que l'on pull master, et ensuite regarder coté rutorrent les changements réalisés.

**Comment by snaj06** [comment]
Merci pour ces précisions !

**Comment by Whisper40** [comment]
J'ai le même cas que toi ou avant je fonctionne avec latest, mais depuis l'épisode des changements qui ont tout cassé de leur côté je passe désormais sur un tag fixe, que je test, et que je change quand j'en ai envie, mais je passe par des tests maintenant avant de faire le changement.

Etant dans un cas avec plusieurs rutorrent, de mon côté je test une version et une fois validée je modifie sur les autres rutorrent.
Donc pour rutorrent j'ai abandonné l'usage de watchtower, mais sinon l'autre solution c'est : 
Tu prends latest, et donc tu gardes watchtower, et le jour ou plus rien ne marche tu fixes un tag qui fonctionne !

**Comment by snaj06** [comment]
Merci pour le tips :)
