### ISSUE TITLE
Bad response from server: (0 [error,getplugins])

### ISSUE THREAD

**Issue by skz000** [mondediefr/docker-rutorrent#47]
After building the image from given .dockerfile, ruTorrent WebUI is broken.
Log section displays: Bad response from server: (0 [error,getplugins])

Can it be that the plugins are directly downloaded from ruTorrent github master branch?
Issue: https://github.com/Novik/ruTorrent/issues/2267

As I understand they are too new for 3.10, it requires to use: 
https://github.com/Novik/ruTorrent/releases/tag/v3.10

**Comment by Hydrog3n** [comment]
Hello @skz000, 

Why do you want to build it? We have the image build already. Also did you have the last version of our repo?
Did you make changes on the dockerfile who can create errors? 

The version 3.10 are in date of juin 2020 so almost 2 years.

**Comment by Whisper40** [comment]
@skz000 You have to clear your cache, the issue will disappear ;) 
Don't forget to use the search function when issues are closed to find this type of problem on this repo, or on rutorrent novik repository.

**Comment by skz000** [comment]
I'm so sorry, I went straight to the very wrong rabbit hole..
