### ISSUE TITLE
Message d'erreur au démarrage et ne garde pas la configuration personnalisée

### ISSUE THREAD

**Issue by zethis** [mondediefr/docker-rutorrent#48]
Hello,
Soucis 7zip au start de la page web
filemanager: Le plug-in ne fonctionnera pas. Le serveur web ne peut pas accéder au(x) programme(s) externe(s). (7z).

De plus ca ne garde pas en mémoire mon changement de thème, à chaque restart il repasse sur le default thème.
Le path data du montage docker à changé ?

**Comment by Whisper40** [comment]
Salut, quel est le tag utilisé ? (ne pas répondre latest) 
Par la même occasion regarde les issues fermées et PR fermées

**Comment by Whisper40** [comment]
Ok je confirme le problème, si tu veux une version fonctionnelle utilise le tag : 2022.01.28
N'hésite pas à poster ce problème ici -> https://github.com/Novik/ruTorrent/issues

**Comment by zethis** [comment]
Le fichier [config.php](https://github.com/mondediefr/docker-rutorrent/blob/master/rootfs/rutorrent/app/conf/config.php) n'est pas à jour avec la version que tu as proposé, et qui à été mergée il y'a peu.

**Comment by Whisper40** [comment]
Je ne comprends pas, ce fichier n'a pas de problème à mon sens..
L'erreur est au niveau de la conf de filemanager
Dans le config.php envoyé, aucun lien avec 7z

**Comment by zethis** [comment]
Non je suis plus sur la problématique du choix du thème non sauvegardé. J'ai checker ta PR.

**Comment by zethis** [comment]
Avec l'update du config.php, plus de soucis de thèmes

**Comment by Whisper40** [comment]
Le fichier config.php est à jour depuis ma PR, donc plus de problème de thème.
Restons sur le problème de 7zip sur cette issue

**Comment by zethis** [comment]
Yes, mais il n'est pas remplacer en cas de montage du volume 'config' par l'utilisateur

**Comment by Whisper40** [comment]
@zethis De mon côté il a bien été remplacé, je n'ai rien eu à faire..
Pour le problème de cette issue, j'ai tenté l'ajout du paquet p7zip sur alpine, puis prendre la nouvelle conf du plugin filemanager mais ce n'est pas fonctionnel..
L'erreur devient : Manipulation des archives désactivée (application introuvable)7z

**Comment by KDTheory** [comment]
J'ai moi aussi le problème de de non sauvegarde de la configuration ou récupération de config existant a chaque redémarrage du conteneur. Serait-il possible de le corriger ? 

De plus le nouveau systeme de tag n'est vraiment pas adapter un systeme versionning serait largement plus utiles

**Comment by Whisper40** [comment]
"Serait-il possible de le corriger ?" -> Je suis désolé, mais c'est bien fonctionnel de mon côté.. Je viens de le re-tester encore aujourd'hui (tag : 2022.02.06 ) 
J'ai modifié les settings, recrée le conteneur, recharger ma page (ctrl+f5) et la config est bien présente, le thème est bien gardé de mon côté..


Malheureusement tu ne donnes aucun argument sur le fait que les tags ne sont "vraiment pas adaptés".
Actuellement, si tu reprends le problème initial, et que tu lis l'ensemble des justifications qui nous ont menées à l'utilisation de ce système tu comprendras que c'est le seul choix possible..

Un système de versioning c'est du côté du projet source.
Nous, on ne fait qu'utiliser leur branche master, à la fois de rutorrent et de filemanager etc.

Si ton argument c'est : "Oui mais le tag marche pas".
Le problème c'est que les repos bougent et donc pour bénéficier à la fois des dernières nouveautés mais garder un moyen de revenir en arrière si un problème est présent c'est la seule solution.

Avec le système précèdent, tu serais resté avec un rutorrent qui ne fonctionne pas pendant des semaines sans aucun moyen de revenir en arrière.

**Comment by KDTheory** [comment]
Je vais tester avec le tag que tu proposes pour voir si ca fonctionne avec cette release. 

Concernant le système de versionning je voulais dire que garder les dates était moins pratique que des releases (ex : v1.x...) 

Par contre je n'avais pas vu le soucis sous cette angle et effectivement je vois pas trop un autre système.... Merci pour la clarification :)
