### ISSUE TITLE
TypeError: this.settings is undefined

### ISSUE THREAD

**Issue by Bono2007** [mondediefr/docker-rutorrent#52]
Problème en redimensionnant les colonnes "Nom" "Statut"
`JS error: [https://xxx/js/webui.js : 892] TypeError: this.settings is undefined`

Ligne correspondante dans webui.js : 
`theWebUI.settings['webui.selected_tab.last'] = theWebUI.activeView;`

**Comment by Whisper40** [comment]
Salut, le signalement est à faire ici si besoin : https://github.com/Novik/ruTorrent
