### ISSUE TITLE
Could you consider adding more theme？

### ISSUE THREAD

**Issue by i-iooi-i** [mondediefr/docker-rutorrent#53]
[club quickbox] is really beautiful, but I don't know how to install it~~
https://github.com/c4pt000/ruTorrent-Themed-install

**Comment by Hydrog3n** [comment]
Hello, 
You can add your themes in the directory mount with /config/custom_themes
We will not provide external theme by default because this can add lot of maintenance on our side who is not good.

**Comment by i-iooi-i** [comment]
> Hello, You can add your themes in the directory mount with /config/custom_themes We will not provide external theme by default because this can add lot of maintenance on our side who is not good.

OK, thank you very much for your reply
