### ISSUE TITLE
How to limit the max number of concurrent downloads ?

### ISSUE THREAD

**Issue by Enissay** [mondediefr/docker-rutorrent#54]
Hi all,
As the title says, how can I set max concurrent download to 5, and if I start downloading 10 torrents, only 5 should be active and 5 queued.
Eventhough I set up a limit from settings, but it is not working as intended :<
![zz](https://user-images.githubusercontent.com/794673/166178369-723128fe-fc6b-4324-9551-33858d38353e.png)
Thanks <3

**Comment by Rathorian** [comment]
Hi,

You would have to modify directly in the file `.rtorrent.rc` which is in the directory you mounted on your docker `/config/rtorrent`.
