### ISSUE TITLE
Erreur depuis la mise à jour mai 2022

### ISSUE THREAD

**Issue by un-breton** [mondediefr/docker-rutorrent#55]
Bonjour, depuis la mise à jour (automatique sous docker) j'ai une erreur, et Rutorrent ne fonctionne plus :

JS error: [https://xxx.xxx.xxx.xxx/js/rtorrent.js : 1116] Uncaught TypeError: xml.getElementsByTagName is not a function

Une idée du probleme ?
Merci !

**Comment by Whisper40** [comment]
Salut, les tags testés et recommandés sont indiqués ici : https://github.com/mondediefr/docker-rutorrent#recommended-tags

Si tu décides d'utiliser la dernière version, tu peut avoir des soucis, tout comme ne pas en avoir ;)
