### ISSUE TITLE
docker config dir - wrong symlink

### ISSUE THREAD

**Issue by Gandulfde** [mondediefr/docker-rutorrent#60]
hi, 
the /configdir is symlinked to /rutorrent/app/share(symlink)
but rutorrent writes the config data to:
/rutorrent/app/php/share.

After an update, all the config files (rss/traffic/usw) are gone. Because the dir /rutorrent/app/php/share is new created.

Can you change the symlink or the rutorrent config dir to /rutorrent/app/share

**Comment by Rathorian** [comment]
Hi,

I'll look into it as soon as I have a moment.
I'll let you know.

Thanks for escalating the issue.

**Comment by Rathorian** [comment]
> hi, the /configdir is symlinked to /rutorrent/app/share(symlink) but rutorrent writes the config data to: /rutorrent/app/php/share.
> 
> After an update, all the config files (rss/traffic/usw) are gone. Because the dir /rutorrent/app/php/share is new created.
> 
> Can you change the symlink or the rutorrent config dir to /rutorrent/app/share

Hi,

I tried to reproduce the problem but even after recreating the container I still have my RSS.

Can you do a PR with the changes to be made and I'll take a look?

Thanks

**Comment by Gandulfde** [comment]
hi, sorry i have no experince with a PR.

here are screenshots of the problem:

![rtorrent1](https://user-images.githubusercontent.com/110632110/184536820-bb1f7498-329d-4e4e-bbc9-94055403b7d3.png)

in this screen is the config of the docker /config that symlinked to the host dir.

![rtorrent2](https://user-images.githubusercontent.com/110632110/184536852-e1bd68c8-a269-4f24-93fd-7e218bf90c95.png)

in this dir rtorrent is writing his config files.

The host dir (in my example /config/rutorent/share) is not used.

**Comment by Rathorian** [comment]
Hi,

Have you tried editing from here: https://github.com/mondediefr/docker-rutorrent/blob/c23ee45cf07578d2201de81d944bbc4075bd8ad4/rootfs/usr/local/bin/startup#L64

To make it look like this to see if it works?

```# Externalize rutorrent share
if [ ! -d /config/rutorrent/share ]; then
  mv /rutorrent/app/share /config/rutorrent
  ln -s /config/rutorrent/share /rutorrent/app/share
fi
```

Cause I can't quite understand
