### ISSUE TITLE
Allow using custom DHT port at start

### ISSUE THREAD

**Issue by Enissay** [mondediefr/docker-rutorrent#61]
Hi all,

I am running the container using a custom port, however, DHT still points to the default one.
```
  -e DHT_RTORRENT=on \
  -e PORT_RTORRENT=7777 \
```
![image](https://user-images.githubusercontent.com/794673/191144446-b1f12dec-a4f0-41a5-98ce-c792503c295b.png)

Would it be possible to add a variable to set it up separately OR make it use the specified `PORT_RTORRENT` by default ?

**Comment by Rathorian** [comment]
Hi,

Problem solved [#68](https://github.com/mondediefr/docker-rutorrent/pull/68)
