### ISSUE TITLE
jQuery TypeError: this.actLbls is undefined

### ISSUE THREAD

**Issue by sa7mon** [mondediefr/docker-rutorrent#7]
Pulling the [latest tag](https://hub.docker.com/layers/mondedie/rutorrent/latest/images/sha256-3281175510b8abad94839ed140845f619b119db40ab4753a0a6da4dbd758f617?context=explore) from Docker Hub and creating a new container results in the following error continuously logged in ruTorrent: 

`[28.03.2020 23:48:36] JS error: [http://localhost:4490/js/jquery.js line 2 > eval : 7082] TypeError: this.actLbls is undefined`

Is ruTorrent outdated in this image?

**Comment by Magicalex** [comment]
Clear the cache in your Web browser?

**Comment by sa7mon** [comment]
Thanks, yeah this appears to be a browser caching issue from trying another rTorrent container earlier. All good now.
