### ISSUE TITLE
Fichier .rotrrent.rc écrasé lors de mise à jour

### ISSUE THREAD

**Issue by Merrick28** [mondediefr/docker-rutorrent#72]
Bonjour,

lors d'une mise à jour (par exemple via watchtower), le fichier .rtorrent.rc est écrasé, et donc supprime les réglages qu'on a pu faire (notamment la variable directory.default.set, ce qui peut être gênant...).

Il faudrait que ce fichier ne soit pas touché lors du démarrage du container, ou bien que l'on puisse mettre en variables les chemins choisis

**Comment by Rathorian** [comment]
Bonjour,

J'imagine que c'est du à ma récente modification #68 
Je devais faire la modification dans le _.rtorrent.rc_ pour prendre en compte les changements.
Malgré tout, j'ai mis en place une copie de sauvegarde du fichier d'origine dans _/config/rtorrent/.rtorrent.rc.old_

Aurais-tu une idée pour faire différemment ?

**Comment by Merrick28** [comment]
Pour moi le plus gênant est le répertoire de destination, le reste n'est pas vital. Du coup, le plus simple serait de mettre en place une nouvelle variable au lancement du torrent (DOWNLOAD_DIRECTORY) et de faire un sed comme tu l'as fait dans le commit indiqué au dessus, en gardant la variable /data/downloads par défaut si cette variable n'est pas settée

Autre solution possible pour éviter la multiplication des variables, dans le startup, quand tu testes l'existence du fichier (ligne 89), tu peux aussi faire un grep de <PORT_DHT> dans ce fichier. Si tu le trouves : le fichier est vierge, on peut intervenir, sinon, le fichier a déjà été configuré, et on ne fait rien.

```
if [ -e /config/rtorrent/.rtorrent.rc ]; then
  if grep -q '<PORT_DHT> config/rtorrent/.rtorrent.rc; then
    
      mv /config/rtorrent/.rtorrent.rc /config/rtorrent/.rtorrent.rc.old
      mv /home/torrent/.rtorrent.rc /config/rtorrent/.rtorrent.rc
      ln -s /config/rtorrent/.rtorrent.rc /home/torrent/.rtorrent.rc
  else
   # fichier déjà present
   ;
  fi
else
  mv /home/torrent/.rtorrent.rc /config/rtorrent/.rtorrent.rc
  ln -s /config/rtorrent/.rtorrent.rc /home/torrent/.rtorrent.rc
fi


```

**Comment by Rathorian** [comment]
On va rester sur ta première solution.
Je ferais la modification un peu plus tard dans la journée

**Comment by Merrick28** [comment]
Testé et validé ! Merci beaucoup :)
