### ISSUE TITLE
Can't change Autotools finished directory 

### ISSUE THREAD

**Issue by sa7mon** [mondediefr/docker-rutorrent#8]
Hi there,

On my docker host I have a directory called "rtorrent-data" which has a "downloads" and "complete" directory beneath it. In my docker-compose.yml file, I have that volume mapped like so:
```
volumes:
      - /rtorrent-data:/data
      - /rtorrent-config:/config
```
In ruTorrent, when I go to change the "path to finished downloads" to "/data/complete", I cannot change it from "/data/downloads/".

![Screen Shot 2020-03-29 at 10 04 09](https://user-images.githubusercontent.com/3712226/77852514-b4326c00-71a4-11ea-9198-89bb30779c21.png)

I can confirm that the "/data/complete" folder does exist inside the container and has the same permissions as "/data/downloads"

**Comment by Magicalex** [comment]
You have 2 solutions

 - first change `directory.default.set = /data` in your .rtorrent.rc
 - or create the `/data/downloads/complete` folder

**Comment by sa7mon** [comment]
Thanks for the quick reply. I followed the first step and also deleted the `.rtorrent` and session folders. It didn't seem to change anything.

I'd really like to keep the `downloads` and `complete` separate

**Comment by Magicalex** [comment]
I undertand but i can do nothing.

You can change your rtorrent.rc see: https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#move-completed-torrents-to-a-fixed-location
Or open a issue on rutorrent repository.
