### ISSUE TITLE
Cannot create 7z archive (same with zip and all the rest)

### ISSUE THREAD

**Issue by dur3x** [mondediefr/docker-rutorrent#81]
Flm\Archive::getCompressBin(): Argument #1 ($type) must be of type string, null given, called in /rutorrent/app/plugins/filemanager/src/Archive.php on line 32

**Comment by Rathorian** [comment]
Hi,

At the moment I can't find a solution.
If anyone has any ideas on how to fix this...

Thanks

**Comment by Rathorian** [comment]
I just deleted the plugin because it is no longer maintained #108
