### ISSUE TITLE
RSS error

### ISSUE THREAD

**Issue by Vendetta1985** [mondediefr/docker-rutorrent#87]
Hello, 
When I create an RSS list and load a torrent from it, I then get an error as soon as I right-click on the RSS list : 
`JS error: [https://www.monsite.com/js/webui.js?v=417 : 1600] TypeError: this.torrents[hash] is undefined`.
Do you have any idea what could be causing this problem? 
Thank you

**Comment by Rathorian** [comment]
> Hello, When I create an RSS list and load a torrent from it, I then get an error as soon as I right-click on the RSS list : `JS error: [https://www.monsite.com/js/webui.js?v=417 : 1600] TypeError: this.torrents[hash] is undefined`. Do you have any idea what could be causing this problem? Thank you

Hi,

I just did a test and everything works correctly with the latest version as of today. RSS torrents load correctly.

If the problem persists, please reopen an issue.
