### ISSUE TITLE
 May I ask when your "mondedie fr/docker-rtorrent" will be updated to Rutorrent4.2.x version.

### ISSUE THREAD

**Issue by lottelucky** [mondediefr/docker-rutorrent#89]
Originally quoted from the rutorrent author's statement when the v4.2.2hotfix version was released. Very much looking forward to your version update.

“It's highly recommended to upgrade for the latest stability improvements. Support for ruTorrent v4.1 will be dropped in the near future. ruTorrent v4.2 has been tested for a few weeks by a large userbase. All known regressions are resolved. It's now more stable and high performing than it's predecessor. ruTorrent v4.1 is inferior at this point time.”

**Comment by Rathorian** [comment]
Hi,

I just added an argument (#90) to specify the version of ruTorrent to use. By default, it uses the latest current version (4.2.3).

**Comment by lottelucky** [comment]
I just updated your image on docker hub, the version number is still 4.1.8. When will the 4.2.3 be updated?

**Comment by Rathorian** [comment]
> I just updated your image on docker hub, the version number is still 4.1.8. When will the 4.2.3 be updated?

It has been up to date for 10 minutes on the HUB.
[st](https://hub.docker.com/layers/mondedie/rutorrent/latest/images/sha256-fc90a4fa96d73d736d42770c6330e5cfbf800a6101b764483f642fdff62aff32?context=explore)

**Comment by lottelucky** [comment]
It has been updated, thank you very much!
